action_id: trunk-cache-prune
date: 2023-09-20 17:49:58
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1695232198
full_timestamp:
  nanos: 157121000
  seconds: 1695232198
trunk_version: 1.15.0
